- ansible.builtin.include_tasks: "systems/{{ ansible_facts['distribution'] }}.yml"
  tags:
    - installation
    - repositories
#
- block:
    - name: Install Syncthing
      ansible.builtin.package:
        name: syncthing
        state: present
      register: syncthing

    - name: Start and enable Syncthing service
      ansible.builtin.systemd_service:
        enabled: true
        name: "syncthing@{{ syncthing_user }}.service"
        state: started
      when:
        - syncthing is succeeded
  when:
    - syncthing_repo is succeeded
  tags:
    - installation
    - packages
