# - ansible.builtin.include_tasks: "systems/{{ ansible_facts['distribution'] }}.yml"
#   tags:
#     - installation
#     - repositories
#
- block:
    - name: Install Syncthing
      ansible.builtin.package:
        name: syncthing
        state: present
      register: syncthing

    - name: Start Syncthing service
      ansible.builtin.systemd_service:
        name: syncthing
        scope: user
        state: started
      when:
        - syncthing is succeeded
      notify:
        - Enable syncthing
  when:
    - syncthing_repo is succeeded
  tags:
    - installation
    - packages
