{{ ansible_managed | comment }}

services:
  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    user: 1000:1000
    environment:
      # - DRY_RUN=true
      - TZ={{ configarr_time_zone }}
    volumes:
      - ./config:/app/config # Contains the config.yml and secrets.yml
      - ./dockerrepos:/app/repos # Cache repositories
      - ./custom/cfs:/app/cfs # Optional if custom formats locally provided
      - ./custom/templates:/app/templates # Optional if custom templates
