---
- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart mediasync service
  ansible.builtin.systemd_service:
    name: "mediasync@{{ mediasync_user }}.service"
    state: restarted
